### ISSUE TITLE
Linter skips _test.go files

### ISSUE THREAD

**Issue by incognick** [SublimeLinter/SublimeLinter-gotype#9]
I can see errors in regular go files but I cannot see errors in my _test.go files in the same package. I tried to use argument "-t" but I get an error:  

```
Traceback (most recent call last):
  File "/Users/nicholasphillips/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 65, in loop
    self.lint(view_id, timestamp)
  File "/Users/nicholasphillips/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 111, in lint
    self.callback(view_id, timestamp)
  File "/Users/nicholasphillips/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 120, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/nicholasphillips/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 929, in lint_view
    linter.lint(hit_time)
  File "/Users/nicholasphillips/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1410, in lint
    for match, line, col, error, warning, message, near in self.find_errors(output):
  File "/Users/nicholasphillips/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 1749, in find_errors
    yield self.split_match(self.regex.match(line.rstrip()))
  File "linter in /Users/nicholasphillips/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-contrib-gotype.sublime-package", line 43, in split_match
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by kaste** [comment]
Sorry, the repo was unmaintained. I at least solved the `None` type error.

**Comment by rasky** [comment]
I can fix this.
